# Generated by Django 4.0.3 on 2022-05-14 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podpodcat',
            options={'ordering': ['id'], 'verbose_name': 'ПодПодкатегория', 'verbose_name_plural': 'ПодПодКатегории'},
        ),
        migrations.AddField(
            model_name='tovar',
            name='users_favorite',
            field=models.ManyToManyField(related_name='favorite_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
