# Generated by Django 4.0.3 on 2022-05-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_podpodcat_options_tovar_users_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='users_favorite',
        ),
        migrations.AddField(
            model_name='user',
            name='user_favorite',
            field=models.ManyToManyField(related_name='favorite_tovari', to='homepage.tovar'),
        ),
    ]
