# Generated by Django 4.0.3 on 2022-05-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_tovar_users_favorite_user_user_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_cart',
            field=models.ManyToManyField(related_name='cart_tovari', to='homepage.tovar'),
        ),
    ]
