# Generated by Django 4.0.3 on 2022-05-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_user_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='open_times',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Сколько раз открыто'),
        ),
    ]
