# Generated by Django 4.0.3 on 2022-05-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_tovar_open_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='open_times',
            field=models.SmallIntegerField(default=0, verbose_name='Сколько раз открыто'),
        ),
    ]
