# Generated by Django 4.0.3 on 2022-05-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_tovar_open_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place_slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
    ]
