# Generated by Django 4.0.3 on 2022-05-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_user_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='place_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
