# Generated by Django 4.0.3 on 2022-05-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_user_place_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='title_small',
            field=models.CharField(max_length=255, null=True, verbose_name='Название товара для поиска'),
        ),
    ]
