# Generated by Django 4.0.3 on 2022-05-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_tovar_title_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='content_small',
            field=models.TextField(null=True, verbose_name='Описание Товара'),
        ),
    ]
